### PR TITLE
Add 'Edit on GitHub' button for each Guide Topic

### LINKED ISSUE #27: Guide: Edit link
Each article should have an edit link, which would redirect the user to a new browser window, where they could edit the article directly, same way as it works at the [Quasar documentation](http://quasar-framework.org/guide/) for example.

### PR DESCRIPTION
**Pull request by erikcr**
Closes #27

### CODE REVIEW

**Comment by kasp1** [comment]
Hi Erik, thank you very much for your contribution.

The link button looks great, but feel free to suggest any styling if you have a better idea. An icon could look good as well.

The link that I get redirected to when I click edit at e.g. the "Installation and setup" edit button is:

`https://github.com/apiko-rest-api/apiko-userguide/blob/master/Installation%20and%20setup.md`

Which displays the file with another edit button, that's absolutely correct! Perhaps we can take it even further if we change the link to:

```
https://github.com/apiko-rest-api/apiko-userguide/edit/master/Installation%20and%20setup.md
                                                  ^^^^
```

After going to this link I get the editor opened straight away, but a regular user should be offered to fork the repository, just like what you see in the Quasar docs if you click the edit link on [this article for example](http://quasar-framework.org/guide/): 

screencapture-github-quasarframework-quasar-framework-org-edit-dev-source-guide-index-md-1493977793750

Do you think it would be possible?

**Comment by erikcr** [comment]
I made the change you suggested so the button now redirects to the /edit page instead of /blob.

**Comment by kasp1** [comment]
Do you see the fork option now when you click the link?

**Comment by erikcr** [comment]
Yes, this is the page that displays when you click the button:

image

**Comment by kasp1** [comment]
Perfect, thank you very much!

**Pull request merged**
